import Scripts.EstadisticaDescriptiva.DesempleoEstadisticaDescriptiva as a1
import Scripts.EstadisticaDescriptiva.SalarioEstadisticaDescriptiva as a2
import Scripts.Estimacion.Estimacion as b
import Scripts.PruebaHipotesis.PruebaHipotesisDesempleo as c1
import Scripts.PruebaHipotesis.PruebaHipotesisSalario as c2

